[2024-06-28T13:58:21.352+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T13:58:21.444+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_sample_dag.task_from_script1 scheduled__2023-08-16T01:55:00+00:00 [queued]>
[2024-06-28T13:58:21.473+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_sample_dag.task_from_script1 scheduled__2023-08-16T01:55:00+00:00 [queued]>
[2024-06-28T13:58:21.474+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T13:58:21.530+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): task_from_script1> on 2023-08-16 01:55:00+00:00
[2024-06-28T13:58:21.562+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1145) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-28T13:58:21.571+0000] {standard_task_runner.py:63} INFO - Started process 1235 to run task
[2024-06-28T13:58:21.572+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_sample_dag', 'task_from_script1', 'scheduled__2023-08-16T01:55:00+00:00', '--job-id', '1791', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp0atpovip']
[2024-06-28T13:58:21.578+0000] {standard_task_runner.py:91} INFO - Job 1791: Subtask task_from_script1
[2024-06-28T13:58:21.740+0000] {task_command.py:426} INFO - Running <TaskInstance: my_sample_dag.task_from_script1 scheduled__2023-08-16T01:55:00+00:00 [running]> on host 81089ac3a69d
[2024-06-28T13:58:22.099+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_sample_dag' AIRFLOW_CTX_TASK_ID='task_from_script1' AIRFLOW_CTX_EXECUTION_DATE='2023-08-16T01:55:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-16T01:55:00+00:00'
[2024-06-28T13:58:22.101+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T13:58:22.106+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T13:58:22.107+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/script1.py", line 10, in function_from_script1
    response = requests.get(url)
                            ^^^
NameError: name 'url' is not defined
[2024-06-28T13:58:22.140+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=my_sample_dag, task_id=task_from_script1, run_id=scheduled__2023-08-16T01:55:00+00:00, execution_date=20230816T015500, start_date=20240628T135821, end_date=20240628T135822
[2024-06-28T13:58:22.193+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 1791 for task task_from_script1 (name 'url' is not defined; 1235)
[2024-06-28T13:58:22.268+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-28T13:58:22.298+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
