[2024-06-28T09:09:25.771+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T09:09:25.947+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_sample_dag.start_streamlit_app scheduled__2023-12-23T00:45:00+00:00 [queued]>
[2024-06-28T09:09:25.998+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_sample_dag.start_streamlit_app scheduled__2023-12-23T00:45:00+00:00 [queued]>
[2024-06-28T09:09:26.002+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T09:09:26.124+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): start_streamlit_app> on 2023-12-23 00:45:00+00:00
[2024-06-28T09:09:26.207+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=730) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-28T09:09:26.252+0000] {standard_task_runner.py:63} INFO - Started process 978 to run task
[2024-06-28T09:09:26.248+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_sample_dag', 'start_streamlit_app', 'scheduled__2023-12-23T00:45:00+00:00', '--job-id', '756', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp3oywef4w']
[2024-06-28T09:09:26.323+0000] {standard_task_runner.py:91} INFO - Job 756: Subtask start_streamlit_app
[2024-06-28T09:09:26.779+0000] {task_command.py:426} INFO - Running <TaskInstance: my_sample_dag.start_streamlit_app scheduled__2023-12-23T00:45:00+00:00 [running]> on host 1d2e3c34485f
[2024-06-28T09:09:27.787+0000] {abstractoperator.py:725} ERROR - Exception rendering Jinja template for task 'start_streamlit_app', field 'bash_command'. Template: 'bash run_streamlit.sh'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 166, in render_template
    template = jinja_env.get_template(value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T09:09:27.801+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2479, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2633, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3094, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 1337, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 166, in render_template
    template = jinja_env.get_template(value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bash run_streamlit.sh
[2024-06-28T09:09:27.881+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=my_sample_dag, task_id=start_streamlit_app, run_id=scheduled__2023-12-23T00:45:00+00:00, execution_date=20231223T004500, start_date=20240628T090925, end_date=20240628T090927
[2024-06-28T09:09:27.998+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 756 for task start_streamlit_app (bash run_streamlit.sh; 978)
[2024-06-28T09:09:28.066+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-28T09:09:28.144+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T09:09:28.168+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
